Repository ethereum/EIP-Bot, pull requests merged in 2022-08, with the labels that each got.

#118 Use EIP-1 rules for Living EIPs
  src/domain/Constants.ts
  src/modules/assertions/__tests__/require_editors.test.ts
  src/modules/assertions/require_editors.ts
Labels: bug, priority: medium

#105 Require multiple editor approvals to merge unknown files
  src/__tests__/Integration.test.ts
  src/modules/assertions/__tests__/require_filename_eip_num.test.ts
  src/modules/assertions/require_filename_eip_num.ts
  src/tests/assets/records/3581.json
  src/tests/assets/records/3670.json
  src/tests/assets/records/4393.json
  src/tests/assets/records/index.ts
Labels: bug, priority: high

#123 Migrate to NodeJS Action
  action.yml
  src/index.ts
Labels: enhancement, priority: medium

#128 Fix "Requested file contains no content" bug
  src/modules/file/modules/get_parsed_content.ts
Labels: bug, priority: low

#129 Bump CI NodeJS version from 14 to 16
  .github/workflows/ci.yml
Labels: bug, priority: low

#130 Update Usage
  README.md
Labels: documentation, priority: low

#135 Remove the adding / removing of labels
  src/main.ts
Labels: enhancement, priority: low

#88 Fail when PR contains more than 100 files
  src/main.ts
  src/modules/assertions/index.ts
  src/modules/assertions/require_max_file_number.ts
Labels: bug, priority: medium
